Replace references to iOS classes with correct Android equivalents.
DataDog/dd-sdk-android pull request #1012
Opened 2022-08-10 10:18 UTC by plousada

### What does this PR do?

Correct documentation containing references to iOS classes

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

2022-08-10 17:18 UTC, buraizu requested changes
Thanks, just made some minor suggestions per our contributing guidelines:
https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md

2022-08-10 17:18 UTC, buraizu commented on docs/mobile_data_collected.md
> +| View     | 30 days   | A view represents a unique screen (or screen segment) on your mobile application. A view starts and stops when the `onActivityResumed` and `onActivityPaused` callbacks are ca
```suggestion
| View     | 30 days   | A view represents a unique screen (or screen segment) on your mobile application. A view starts and stops when the `onActivityResumed` and `onActivityPaused` callbacks are called through the `ActivityLifecycleCallbacks` interface. Each occurrence is classified as a distinct view. While a user stays on a view, RUM event attributes (Errors, Resources, Actions) get attached to the view with a unique `view.id`.                     |
```

2022-08-11 15:45 UTC, buraizu approved these changes

2022-08-12 08:05 UTC, mariusc83 approved these changes

2022-08-12 09:21 UTC, merged