DOCS-3982 Android Integrated Libraries Update
DataDog/dd-sdk-android pull request #1021
Opened 2022-08-25 18:42 UTC by alai97

### What does this PR do?

Surface the Jetpack Compose integration in the integrated libraries page and list of RUM integrations.

### Motivation

#support-rum Slack

### Additional Notes

Anything else we should know when reviewing?

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

2022-08-25 21:22 UTC, apigirl approved these changes

2022-08-26 06:55 UTC, xgouchet approved these changes

2022-08-26 07:17 UTC, 0xnm requested changes

2022-08-26 07:17 UTC, 0xnm commented on README.md
> +If you use Jetpack Compose to load images in your application, take a look at Datadog's [dedicated library](dd-sdk-android-compose/README.md).
it seems here is a copy-paste mistake from the Glide integration above. Jetpack Compose is not a library for loading images, it is a [UI toolkit framework](https://developer.android.com/jetpack/compose). I suppose the part about loading images should be deleted:

```suggestion
If you use Jetpack Compose in your application, take a look at Datadog's [dedicated library](dd-sdk-android-compose/README.md).
```

2022-08-26 07:17 UTC, 0xnm commented on docs/integrated_libraries_android.md
> +If you use Jetpack Compose to load images in your application, take a look at Datadog's [dedicated Jetpack Compose library][7].
same as previous suggestion

```suggestion
If you use Jetpack Compose in your application, take a look at Datadog's [dedicated Jetpack Compose library][7].
```

2022-08-29 06:10 UTC, 0xnm approved these changes

2022-08-29 06:25 UTC, xgouchet approved these changes

2022-08-29 17:37 UTC, merged