DOCS-5147 Android Log Collection Edit
DataDog/dd-sdk-android pull request #1380
Opened 2023-04-12 19:25 UTC by alai97

### What does this PR do?

Adds a tab for the AP1 site region.

### Motivation

DOCS-5147

### Additional Notes

Anything else we should know when reviewing?

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [x] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

2023-04-12 22:59 UTC, rtrieu requested changes
Added a minor suggestion, but otherwise looks good.

2023-04-12 22:59 UTC, rtrieu commented on docs/log_collection.md
> +2. Initialize the library with your application context, tracking consent, as well as the [Datadog client token][2] and Application ID provided when you [created a RUM application][6]. For security r
```suggestion
2. Initialize the library with your application context, tracking consent, as well as the [Datadog client token][2] and Application ID provided when you [created a RUM application][6]. For security reasons, you must use a client token; you cannot use [Datadog API keys][3] to configure the `dd-sdk-android` library, as they would be exposed client-side in the Android application APK byte code.
```

2023-04-13 07:34 UTC, 0xnm approved these changes
lgtm, I've added some formatting suggestions

2023-04-13 07:34 UTC, 0xnm commented on docs/log_collection.md
> +               APPLICATION_ID >);
```suggestion
               Credentials credentials = new Credentials(<CLIENT_TOKEN>, <ENV_NAME>, <APP_VARIANT_NAME>, <APPLICATION_ID>);
```

2023-04-13 07:34 UTC, 0xnm commented on docs/log_collection.md
> +               APPLICATION_ID >);
```suggestion
               Credentials credentials = new Credentials(<CLIENT_TOKEN>, <ENV_NAME>, <APP_VARIANT_NAME>, <APPLICATION_ID>);
```

2023-04-13 07:34 UTC, 0xnm commented on docs/log_collection.md
> +               APPLICATION_ID >);
```suggestion
               Credentials credentials = new Credentials(<CLIENT_TOKEN>, <ENV_NAME>, <APP_VARIANT_NAME>, <APPLICATION_ID>);
```

2023-04-13 07:34 UTC, 0xnm commented on docs/log_collection.md
> +               APPLICATION_ID >);
```suggestion
               Credentials credentials = new Credentials(<CLIENT_TOKEN>, <ENV_NAME>, <APP_VARIANT_NAME>, <APPLICATION_ID>);
```

2023-04-13 07:34 UTC, 0xnm commented on docs/log_collection.md
> +               APPLICATION_ID >);
```suggestion
               Credentials credentials = new Credentials(<CLIENT_TOKEN>, <ENV_NAME>, <APP_VARIANT_NAME>, <APPLICATION_ID>);
```

2023-04-13 07:34 UTC, 0xnm commented on docs/log_collection.md
> +               APPLICATION_ID >);
```suggestion
               Credentials credentials = new Credentials(<CLIENT_TOKEN>, <ENV_NAME>, <APP_VARIANT_NAME>, <APPLICATION_ID>);
```

2023-04-13 08:32 UTC, xgouchet approved these changes

2023-04-13 16:42 UTC, rtrieu approved these changes
Nice!

2023-04-13 20:34 UTC, merged