[RUMM-3148] Include builder options for Android Tracer
DataDog/dd-sdk-android pull request #1436
Opened 2023-05-24 14:46 UTC by plousada

### What does this PR do?

Introduce the builder configuration parameters for the Android Tracer.

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

2023-05-24 15:49 UTC, xgouchet approved these changes

2023-05-24 15:54 UTC, 0xnm approved these changes

2023-05-24 15:54 UTC, 0xnm commented on docs/trace_collection.md
> +The following methods in AndroidTracer.Builder can be used when initializing the Tracer:
probably it is better to highlight code parts:

```suggestion
The following methods in `AndroidTracer.Builder` can be used when initializing the `Tracer`:
```

2023-05-24 16:34 UTC, drichards-87 requested changes
Left you some light feedback from docs.

2023-05-24 16:34 UTC, drichards-87 commented on docs/trace_collection.md
> +| `setSamplingRate(<FLOAT>)`   | Set a value `0-100` in order to define the percentage of Traces to collect. |
```suggestion
| Method                           | Description                                                                                                                                                                                                                         |
|----------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `setServiceName(<SERVICE_NAME>)	`    | Set the value for the `service`. |
| `setPartialFlushThreshold(<INT>)` |  When this threshold is reached (you have a specific `<INT>` amount of spans closed waiting), the flush mechanism is triggered and all pending closed spans are processed and sent to intake.|
| `addGlobalTag(<KEY>, <VALUE>)`     | Set the `<KEY>:<VALUE>` pair of tags to be added to spans created by the Tracer. |
| `setBundleWithRumEnabled(true)`    | Set to `true` to enable spans to be enriched with the current RUM View information. This enables you to see all of the spans produced during a specific View lifespan in the RUM Explorer. |
| `setSamplingRate(<FLOAT>)`   | Set a value `0-100` to define the percentage of Traces to collect. |
```

2023-05-25 14:44 UTC, drichards-87 approved these changes

2023-06-01 07:40 UTC, jonathanmos approved these changes

2023-06-07 13:47 UTC, merged