RUMM-3406: Prepare release 2.0.0-beta1
DataDog/dd-sdk-android pull request #1532
Opened 2023-07-07 08:45 UTC by 0xnm

### What does this PR do?

This PR prepares release `2.0.0-beta1`.

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

2023-07-07 20:54 UTC, urseberry requested changes

2023-07-07 20:54 UTC, urseberry commented on CHANGELOG.md
> +This is the first release of SDK v2. It contains breaking changes related to the SDK setup and APIs, please check [migration guide](https://github.com/DataDog/dd-sdk-android/blob/8c998bdf53239b262151
```suggestion
This is the first release of SDK v2. It contains breaking changes related to the SDK setup and APIs. See the [migration guide](https://github.com/DataDog/dd-sdk-android/blob/8c998bdf53239b2621518ea1225c9987eb4db85d/MIGRATION.MD) for details.
```

2023-07-07 20:54 UTC, urseberry commented on docs/sdk_benchmarks.md
> +**Note**: This document is outdated, it will be updated later.
This line isn't appropriate for our public docs. If you don't have time to update now, can you remove the out of date parts, and perhaps replace them with a summary? It's better to have incomplete docs than incorrect ones.

2023-07-07 20:54 UTC, urseberry commented on docs/sdk_performance.md
> +**Note**: This document is outdated, it will be updated later.
This line isn't appropriate for our public docs. If you don't have time to update now, can you remove the out of date parts, and perhaps replace them with a summary? It's better to have incomplete docs than incorrect ones.

2023-07-10 07:56 UTC, xgouchet approved these changes

2023-07-10 08:02 UTC, mariusc83 approved these changes

2023-07-10 08:03 UTC, jonathanmos approved these changes

2023-07-10 08:13 UTC, merged