RUM-2014 Add the synchronous equivalent of readNextBatch and confirmBatchRead in Storage API
DataDog/dd-sdk-android pull request #1768
Opened 2023-12-15 08:59 UTC by mariusc83

In this PR we are replacing the async methods `readNextBatch` and `confirmBatchRead` from `Storage` interface with their synchronous equivalents. 

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

2023-12-15 13:20 UTC, xgouchet requested changes
> [!WARNING]
> We still have asynchronous `confirmBatchRead` in the DataUploader, so we might want to also have a synchronous method there WDYT?

2023-12-15 14:03 UTC, mariusc83 commented
> Warning
> 
> We still have asynchronous `confirmBatchRead` in the DataUploader, so we might want to also have a synchronous method there WDYT?

I actually wanted to do that but then @0xnm said that it might still have sense to call that method only with a callback. 
@0xnm what do you think ?

2023-12-19 08:26 UTC, xgouchet approved these changes

2023-12-19 10:41 UTC, 0xnm approved these changes
lgtm! need also to delete duplicate `DataUploader`, `DataFlusher`, etc. files.

2023-12-19 10:45 UTC, jonathanmos approved these changes

2023-12-19 13:45 UTC, merged