RUM-2207 Call RUM error mapper even for crashes
DataDog/dd-sdk-android pull request #1945
Opened 2024-03-27 13:59 UTC by fuzzybinary

### What does this PR do?

This changes the RUM error event mapper to call the user supplied mapper even for crashes, which it previously excluded.

The error event mapper still does not support discarding fatal errors, and a warning is sent if the user returns null for a fatal error in the mapper.

### Additional Notes

Anything else we should know when reviewing?

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

2024-03-27 18:27 UTC, xgouchet requested changes

2024-03-27 18:27 UTC, xgouchet commented on features/dd-sdk-android-rum/src/main/kotlin/com/datadog/android/rum/internal/domain/event/RumEventMapper.kt
> +                    }
> [!IMPORTANT]
> Could you add the tests for this use case ?

2024-03-28 15:36 UTC, 0xnm approved these changes

2024-03-29 10:40 UTC, xgouchet approved these changes

2024-03-29 13:21 UTC, merged