RUM-5553: Create Benchmark module to collect performance metrics
DataDog/dd-sdk-android pull request #2141
Opened 2024-07-24 11:32 UTC by ambushwork

### What does this PR do?

Creates a module in SDK for the metrics benchmarks

### Motivation

[RUM-5553]

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

2024-07-24 12:25 UTC, xgouchet requested changes

2024-07-24 12:25 UTC, xgouchet commented on settings.gradle.kts
> +include(":benchmark")
> [!NOTE]
> Let's make it a `:tools:benchmark`  module instead to limit the number of top level folders in the repo

2024-07-24 14:00 UTC, ambushwork commented on settings.gradle.kts
> +include(":benchmark")
updated

2024-07-25 06:59 UTC, mariusc83 approved these changes

2024-07-25 07:30 UTC, xgouchet approved these changes

2024-07-25 08:10 UTC, merged

2024-08-12 15:12 UTC, 0xnm commented on tools/benchmark/build.gradle.kts
> +    api(libs.openTelemetryApi)
this probably should be `implementation`, unless we want to re-export definitions in some module which will consume this one

2024-08-12 15:12 UTC, 0xnm commented on tools/benchmark/build.gradle.kts
> +    compileOnly(libs.detektApi)
is it needed?

2024-08-12 15:12 UTC, 0xnm commented on tools/benchmark/build.gradle.kts
> +    testImplementation(libs.detektTest)
and this is not needed as well, I guess.

2024-08-12 15:12 UTC, 0xnm commented on tools/benchmark/build.gradle.kts
> +    testImplementation(libs.robolectric)
probably also not needed?