Add README for benchmark module and benchmark sample application
DataDog/dd-sdk-android pull request #2167
Opened 2024-08-05 12:35 UTC by ambushwork

### What does this PR do?

Add README for benchmark module and benchmark sample application

### Motivation

[RUM:5553]
[RUM:5550]

### Additional Notes

Anything else we should know when reviewing?

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

2024-08-05 19:25 UTC, rtrieu requested changes
Some feedback for your review!

2024-08-05 19:25 UTC, rtrieu commented on sample/benchmark/README.md
> +This is a sample application for Datadog internal use to benchmarking the overhead of SDK features.
```suggestion
This is a sample application for Datadog internal use to benchmark the overhead of SDK features.
```

2024-08-05 19:25 UTC, rtrieu commented on sample/benchmark/README.md
> +The application will be uploaded for every commit in `develop` branch to continuously monitor the
```suggestion
The application is uploaded for every commit in `develop` branch to continuously monitor the
```

2024-08-05 19:25 UTC, rtrieu commented on sample/benchmark/README.md
> +overhead of the SDK in case of any spike on cpu usage, memory usage or FPS.
```suggestion
overhead of the SDK in case of any spike on CPU usage, memory usage or FPS.
```

2024-08-05 19:25 UTC, rtrieu commented on sample/benchmark/README.md
> +arguments needed to be defined in order to control the scenario which should be measured. for
```suggestion
arguments needed to be defined in order to control the scenario that should be measured. for
```

2024-08-05 19:25 UTC, rtrieu commented on sample/benchmark/README.md
> +example if the test target is Session Replay here is the intent arguments for the baseline test:
```suggestion
example, if the test target is Session Replay, here are the intent arguments for the baseline test:
```

2024-08-05 19:25 UTC, rtrieu commented on tools/benchmark/README.md
> +This is a module for Datadog internal use to benchmarking the overhead of SDK features.
```suggestion
This is a module for Datadog internal use to benchmark the overhead of SDK features.
```

2024-08-05 19:25 UTC, rtrieu commented on tools/benchmark/README.md
> +Currently the gauge that it measures includes CPU ticks, memory usage and FPS of the application.
```suggestion
Currently the gauge that it measures includes CPU ticks, memory usage, and FPS of the application.
```

2024-08-05 19:25 UTC, rtrieu commented on tools/benchmark/README.md
> +1. Build Datadog exporter configuration
```suggestion
1. Build the Datadog exporter configuration:
```

2024-08-05 19:25 UTC, rtrieu commented on tools/benchmark/README.md
> +2. Create `DatadogMeter` with configuration
```suggestion
2. Create `DatadogMeter` with the configuration:
```

2024-08-05 19:25 UTC, rtrieu commented on tools/benchmark/README.md
> +3. Start all gauges with meter
```suggestion
3. Start all gauges with meter:
```

2024-08-05 19:25 UTC, rtrieu commented on tools/benchmark/README.md
> +4. Stop all gauges with meter
```suggestion
4. Stop all gauges with meter:
```

2024-08-05 19:25 UTC, rtrieu commented on tools/benchmark/README.md
> +through [Datadog submit metrics API](https://docs.datadoghq.com/api/latest/metrics/#submit-metrics),
```suggestion
through [Datadog submit metrics API](https://docs.datadoghq.com/api/latest/metrics/#submit-metrics).
```

2024-08-07 07:47 UTC, jonathanmos approved these changes

2024-08-07 07:47 UTC, jonathanmos commented on sample/benchmark/README.md
> +overhead of the SDK in case of any spike on CPU usage, memory usage or FPS.
```suggestion
overhead of the SDK in case of any spike in CPU usage, memory usage or FPS.
```

2024-08-07 07:47 UTC, jonathanmos commented on sample/benchmark/README.md
> +under `config/` folder of root path:
```suggestion
under the `config/` folder in the root path:
```

2024-08-07 07:47 UTC, jonathanmos commented on tools/benchmark/README.md
> +Currently the gauge that it measures includes CPU ticks, memory usage, and FPS of the application.
```suggestion
Currently the gauges that it measures include CPU ticks, memory usage, and FPS of the application.
```

2024-08-07 07:47 UTC, jonathanmos commented on tools/benchmark/README.md
> +The metrics name for each gauge:
```suggestion
The metric names for each gauge:
```

2024-08-07 07:47 UTC, jonathanmos commented on tools/benchmark/README.md
> +* [android.benchmark.fps]: Frame per second
```suggestion
* [android.benchmark.fps]: Frames per second
```

2024-08-07 11:22 UTC, jonathanmos approved these changes

2024-08-07 14:01 UTC, rtrieu requested changes
Found a few more things!

2024-08-07 14:01 UTC, rtrieu commented on tools/benchmark/README.md
> +Currently the gauges that it measures include CPU ticks, memory usage, and FPS of the application.
```suggestion
It measures gauges that include CPU ticks, memory usage, and FPS of the application.
```

2024-08-07 14:30 UTC, ambushwork commented
@rtrieu I just updated all of the requested changes, please recheck it again, thanks!

2024-08-07 15:02 UTC, rtrieu commented on sample/benchmark/README.md
> +If you want to run the application locally, a `benchmark.json` file needs to be created
```suggestion
If you want to run the application locally, create a `benchmark.json` file with the following contents
```

2024-08-07 15:03 UTC, rtrieu approved these changes
One more comment, but approving.

2024-08-07 15:57 UTC, ambushwork commented on sample/benchmark/README.md
> +If you want to run the application locally, a `benchmark.json` file needs to be created
updated!

2024-08-07 16:22 UTC, rtrieu approved these changes
Approving!

2024-08-07 16:29 UTC, merged