RUMM-741 Provide SQLiteDatabase#transactionTraced extension function
DataDog/dd-sdk-android pull request #386
Opened 2020-09-28 15:35 UTC by mariusc83

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

2020-09-28 21:26 UTC, ruthnaebeck requested changes
docs review

2020-09-28 21:26 UTC, ruthnaebeck commented on dd-sdk-android-ktx/README.md
> +If you are using SQLiteDatabase to persist your data locally, you can trace the database transaction using the following method:
```suggestion
If you are using SQLiteDatabase to persist data locally, you can trace the database transaction using the following method:
```

2020-09-28 21:26 UTC, ruthnaebeck commented on dd-sdk-android-ktx/README.md
> +It behaves as the `SQLiteDatabase.transaction` method provided in the `core-ktx` AndroidX package and only requires a span operation name.
```suggestion
It behaves like the `SQLiteDatabase.transaction` method provided in the `core-ktx` AndroidX package and only requires a span operation name.
```

2020-09-29 09:45 UTC, xgouchet approved these changes
Mostly naming and KDoc comments 👍

2020-09-29 14:48 UTC, merged