RUMM-838 Introduce the basic BatchedDataMigrator implementations
DataDog/dd-sdk-android pull request #405
Opened 2020-11-09 14:47 UTC by mariusc83

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

2020-11-10 13:22 UTC, xgouchet requested changes
Overall good job Marius, just a few comments :)

2020-11-10 15:55 UTC, mariusc83 commented on dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/file/FileHandler.kt
> +    fun clearFile(source: File): Boolean {
This is a wrapper over the system method which works also with a File. I will rename that method instead ;)

2020-11-10 15:55 UTC, mariusc83 commented on dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/file/FileHandler.kt
> +    fun moveFiles(sourceDirectory: File, destinationDirectory: File): Boolean {
Good call

2020-11-10 15:56 UTC, mariusc83 commented on dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/data/file/FileHandler.kt
> +        } catch (e: NullPointerException) {
I am not sure is just that if you check the Java docs for the `rename` method it specifies that it can throw a NPE. Better safe than sorry.

2020-11-10 15:57 UTC, mariusc83 commented on dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/domain/batching/migrators/WipeDataMigrator.kt
> +        }
Actually was waiting for your comment here. I was thinking the same then I thought that it is a bit overkill to add a retry here only for this delete operation.

2020-11-12 11:13 UTC, xgouchet approved these changes

2020-11-12 13:30 UTC, merged