RUMM-893 Add variant tag
DataDog/dd-sdk-android pull request #443
Opened 2020-12-14 22:01 UTC by xgouchet

### What does this PR do?

Adds a `variant` tag to the RUM events.

Because the DatadogConfig class gets a bit messy, I split it into two classes: `Credentials` (to store info that will rarely change) and `Configuration` for features parameters.

2020-12-15 13:40 UTC, mariusc83 requested changes

2020-12-15 13:40 UTC, mariusc83 commented on dd-sdk-android/src/test/kotlin/com/datadog/android/core/internal/SdkFeatureTest.kt
> +    lateinit var fakeConfig: C
maybe we should rename this `fakeConfigurationFeature`

2020-12-16 07:20 UTC, xgouchet commented on dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/event/NoOpEventMapper.kt
> +    override fun equals(other: Any?): Boolean {
Because these are used for tests purposes

2020-12-16 07:22 UTC, xgouchet commented on dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/SdkFeature.kt
> +    open fun onInitialize(context: Context, configuration: C) {}
Why do you want people to call super, when the default implementation is empty ?

2020-12-16 07:31 UTC, mariusc83 commented on dd-sdk-android/src/main/kotlin/com/datadog/android/core/internal/SdkFeature.kt
> +    open fun onInitialize(context: Context, configuration: C) {}
No...that's the thing...in order to make sure that when `onInitialize` is executed we do not forget to mark that flag to true we could have a default implementation here in the abstract class where we update that flag and then in the child class we force the call on the super when implementing that function.

2020-12-16 08:14 UTC, xgouchet commented on dd-sdk-android/src/main/kotlin/com/datadog/android/Configuration.kt
> +    class Builder(
Done

2020-12-16 09:22 UTC, mariusc83 approved these changes

2020-12-17 08:25 UTC, merged