RUMM-979 PokoGenerator generate Type::fromJson deserializer method
DataDog/dd-sdk-android pull request #467
Opened 2021-01-12 19:32 UTC by mariusc83

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

2021-01-13 19:47 UTC, xgouchet requested changes

2021-01-13 19:47 UTC, xgouchet commented on buildSrc/src/test/kotlin/com/example/model/Article.kt
> +                ,authors
There's something wrong with the code style here.

2021-01-14 08:03 UTC, mariusc83 commented on buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/PokoDeserializerGenerator.kt
> +            is TypeDefinition.Null -> funBuilder.addStatement("val %L = null", property.name.trim())
it was acting weirdly without the trim, placing the variables with indents between them. I am going to try with the varName instead.

2021-01-14 08:04 UTC, mariusc83 commented on buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/PokoDeserializerGenerator.kt
> +    @Suppress("NON_EXHAUSTIVE_WHEN")
I think I just copy pasted this one from a previous one, I will remove that and add an JsonParse exception there.

2021-01-14 08:05 UTC, mariusc83 commented on buildSrc/src/test/kotlin/com/example/model/Style.kt
> +                )
Yeah.....not really sure how to fix that and didn't want to spend too much time on that for now. I will have another look.

2021-01-14 08:07 UTC, mariusc83 commented on buildSrc/src/main/kotlin/com/datadog/gradle/plugin/jsonschema/PokoDeserializerGenerator.kt
> +            "%T.valueOf(it.toUpperCase(%T.US).replace(%T(\"[^A-Z0-9]+\"), \"_\"))",
yeah...I don't like it either. What do you think about providing 2 extension methods in a separated file:
```fun String.toJsonValue()
     fun String.toEnumValue()
```

2021-01-14 16:12 UTC, xgouchet approved these changes

2021-01-14 17:09 UTC, merged