RUMM-1133 δ internal monitoring
DataDog/dd-sdk-android pull request #524
Opened 2021-03-11 12:41 UTC by xgouchet

### What does this PR do?

Provide a mecanism to send internal logs to our own datadog org.

2021-03-15 11:50 UTC, mariusc83 requested changes

2021-03-15 18:16 UTC, xgouchet commented on dd-sdk-android/src/main/kotlin/com/datadog/android/monitoring/internal/InternalLogsFeature.kt
> +
In the Logger class

2021-03-16 08:20 UTC, 0xnm approved these changes

2021-03-16 15:49 UTC, xgouchet commented on dd-sdk-android/src/main/kotlin/com/datadog/android/core/configuration/Configuration.kt
> +            endpointUrl: String
No this is not a limited set of values: people could set custom endpoints if they want

2021-03-16 15:53 UTC, mariusc83 approved these changes

2021-03-16 15:54 UTC, merged