reviewed docs to fix broken table, images and links
DataDog/dd-sdk-android pull request #570
Opened 2021-04-21 20:29 UTC by priyanshi-gupta

### What does this PR do?

A brief description of the change being made with this pull request.
Fixed broken links, images and tables in documentation.

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

2021-04-21 20:35 UTC, xgouchet requested changes

2021-04-21 20:35 UTC, xgouchet commented on docs/rum_getting_started.md
> +      }
This part of not required anymore and should be removed

2021-04-21 20:35 UTC, xgouchet commented on docs/rum_getting_started.md
> +      dependencies { implementation "com.datadoghq:dd-sdk-android:x.x.x"
Usually the dependencies block should go after the plugins

2021-04-21 20:53 UTC, kayayarai requested changes
one tiny missing #

2021-04-21 20:53 UTC, kayayarai commented on docs/configure_rum_android_sdk.md
> +[5]: /real_user_monitoring/android/advanced_configuration/initialization-parameters
```suggestion
[5]: /real_user_monitoring/android/advanced_configuration/#initialization-parameters
```

2021-04-21 22:42 UTC, kayayarai approved these changes

2021-04-22 06:36 UTC, mariusc83 approved these changes

2021-04-22 06:36 UTC, mariusc83 commented on docs/rum_getting_started.md
> +    dependencies { implementation "com.datadoghq:dd-sdk-android:x.x.x"
I think the code format is broken here

2021-04-22 13:32 UTC, xgouchet requested changes

2021-04-22 13:32 UTC, xgouchet commented on docs/rum_getting_started.md
> +    }
```suggestion
dependencies {
    implementation "com.datadoghq:dd-sdk-android:x.x.x" 
}
```

2021-04-22 15:07 UTC, xgouchet approved these changes

2021-04-22 15:28 UTC, merged