RUMM-1091: Update code samples in docs to make it up-to-date, fix formatting
DataDog/dd-sdk-android pull request #585
Opened 2021-05-03 13:52 UTC by 0xnm

### What does this PR do?

This changes updates code samples in docs to make it up-to-date and match the actual API.

2021-05-03 13:55 UTC, xgouchet approved these changes

2021-05-03 20:38 UTC, kayayarai requested changes

2021-05-03 20:38 UTC, kayayarai commented on docs/configure_rum_android_sdk.md
> +   |               | `view.name           | Name of the view                                |
```suggestion
   |               | `view.name`           | Name of the view                                |
```

2021-05-03 20:38 UTC, kayayarai commented on docs/configure_rum_android_sdk.md
> +   |               | `view.name           | Name of the view                                |
```suggestion
   |               | `view.name`           | Name of the view                               |
```

2021-05-03 20:38 UTC, kayayarai commented on docs/configure_rum_android_sdk.md
> +   |               | `view.name           | Name of the view                                |
```suggestion
   |               | `view.name`           | Name of the view                                |
```

2021-05-03 20:38 UTC, kayayarai commented on docs/configure_rum_android_sdk.md
> +   |               | `view.name           | Name of the view                                |
```suggestion
   |               | `view.name`           | Name of the view                                |
```

2021-05-10 08:05 UTC, mariusc83 approved these changes

2021-05-10 16:50 UTC, kayayarai approved these changes

2021-05-10 17:45 UTC, merged