RUMM-1384: Add statement about minimum supported version to the official docs
DataDog/dd-sdk-android pull request #615
Opened 2021-05-27 14:35 UTC by 0xnm

### What does this PR do?

This changes adds the statement about minimum supported OS version. It is added at the similar place as for the Browser SDK https://docs.datadoghq.com/real_user_monitoring/browser/, right after initial Setup block.

2021-05-27 19:09 UTC, ruthnaebeck requested changes
Docs review

2021-05-27 19:09 UTC, ruthnaebeck commented on docs/rum_getting_started.md
> +**Minimum Android OS version**: Datadog SDK for Android supports Android OS starting from version 19.
```suggestion
**Minimum Android OS version**: Datadog SDK for Android supports Android OS v19+.
```

2021-05-28 14:38 UTC, xgouchet approved these changes

2021-06-01 11:34 UTC, xgouchet approved these changes

2021-06-02 13:26 UTC, merged