RUMM-1488 US5 endpoints
DataDog/dd-sdk-android pull request #685
Opened 2021-08-24 09:45 UTC by xgouchet

### What does this PR do?

Add support to the US5 endpoints

2021-08-24 18:55 UTC, cswatt requested changes

2021-08-24 18:55 UTC, cswatt commented on sample/README.md
> +For each flavor you will have to provide a config file named `[flavorName].json`. By default, flavors should match one of the existing site in the `DatadogSite` enum (i.e.: `us1`, `us1_fed`, `us3`, `
```suggestion
For each flavor, you must provide a config file named `[flavorName].json`. By default, flavors should match one of the existing site in the `DatadogSite` enum (i.e.: `us1`, `us1_fed`, `us3`, `us5`, `eu1`).
```

2021-08-24 18:55 UTC, cswatt commented on sample/README.md
> +In order to allow the download of logs (to test the `Data List` screen), you need to add the following attributes (you'll find them in the `Organization Settings` page on Datadog's website):
```suggestion
To allow the download of logs (to test the `Data List` screen), add the following attributes. You can find them in the `Organization Settings` page in Datadog.
```

2021-08-24 18:55 UTC, cswatt commented on sample/README.md
> +If you want to enable the internal monitoring, you need to add the relevant clientToken in the following attribute:
```suggestion
If you want to enable the internal monitoring, you need to add the relevant `clientToken` in the following attribute: 
```

2021-08-24 18:56 UTC, cswatt approved these changes
looks good for docs!

2021-08-25 11:59 UTC, ncreated approved these changes

2021-08-30 10:19 UTC, 0xnm approved these changes
lgtm! I've added just 2 very minor points.

2021-08-30 10:19 UTC, 0xnm commented on sample/kotlin/build.gradle.kts
> +        register("us1_fed") {
minor: maybe we can just write something like this:

```
arrayOf("us1_fed", "us3", "us5", "eu1").forEach { register(it) { ... } }
```

2021-08-30 10:19 UTC, 0xnm commented on buildSrc/src/main/kotlin/com/datadog/gradle/config/FlavorBuildConfig.kt
> +            "\"${flavor.name.toUpperCase()}\""
very nit: usage of `toUpperCase` without locale is discouraged - it may lead to unexpected results on some user locales.

2021-09-06 09:55 UTC, merged