Add mobile vitals screen to sample
DataDog/dd-sdk-android pull request #697
Opened 2021-09-06 13:54 UTC by xgouchet

### What does this PR do?

Support US5 endpoints

2021-09-06 17:06 UTC, mariusc83 requested changes

2021-09-06 17:06 UTC, mariusc83 commented on dd-sdk-android/src/main/kotlin/com/datadog/android/DatadogEndpoint.kt
> +    const val LOGS_US5: String = "https://logs.browser-intake-us5-datadoghq.com"
you're still having these changes in this PR ?

2021-09-07 11:41 UTC, mariusc83 approved these changes

2021-09-07 11:50 UTC, 0xnm approved these changes

2021-09-07 18:32 UTC, alai97 approved these changes
Looks good pending this small nit!

2021-09-07 18:32 UTC, alai97 commented on sample/README.md
> +For each flavor, you must provide a config file named `[flavorName].json`. By default, flavors should match one of the existing sites in the `DatadogSite` enum (i.e.: `us1`, `us1_fed`, `us3`, `us5`,
```suggestion
For each flavor, you must provide a config file named `[flavorName].json`. By default, flavors should match one of the existing sites in the `DatadogSite` enum (for example: `us1`, `us1_fed`, `us3`, `us5`, `eu1`).
```

2021-09-14 08:52 UTC, merged