RUMM-1529 Add remaining nightly tests for Logs feature
DataDog/dd-sdk-android pull request #699
Opened 2021-09-08 08:44 UTC by mariusc83

### What does this PR do?

In this PR we are completing the nightly tests coverage for Logs feature.

### Additional Notes

The following updates were added:

- Nightly test coverage and monitors added for `com.datadog.android.log.Logger#fun addAttribute(String, Long)`, `com.datadog.android.log.Logger#fun addTag(String)`, `com.datadog.android.log.Logger#fun removeTagsWithKey(String)` API entries
- The `methodSignature` was fixed for test coverage tool for the following API entries: `com.datadog.android.log.Logger#fun addAttribute(String, com.google.gson.JsonArray?)`, `com.datadog.android.log.Logger#fun addAttribute(String, com.google.gson.JsonObject?), `com.datadog.android.log.Logger#fun addAttribute(String, java.util.Date?)`
- The test coverage threshold was increased to `0.76`

2021-09-08 11:54 UTC, xgouchet requested changes

2021-09-08 11:54 UTC, xgouchet commented on instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/logs/LoggerE2ETests.kt
> +            "$SPECIAL_BUNDLED_TAG_NAME:${forge.aStringMatching("customTag[a-z0-9_:./-]{1,20}")}"
for readability, can you export the tag generation into a variable?

2021-09-08 12:27 UTC, 0xnm approved these changes

2021-09-08 12:27 UTC, 0xnm commented on instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/logs/LoggerE2ETests.kt
> +        val tagValue = forge.aStringMatching("customTag[a-z0-9_:./-]{1,20}")
I don't know how it affects performance, but in the recent change https://github.com/DataDog/dd-sdk-android/pull/698/files#diff-5a71e55cb00745521b8ca794d4d35ef852cd45d987fe4b56d45ea5e94e3408f1 constant part was extracted from `aStringMatching` argument. Maybe need to do the same here for the consistency?

2021-09-10 08:12 UTC, xgouchet requested changes

2021-09-10 08:12 UTC, xgouchet commented on instrumented/nightly-tests/src/androidTest/kotlin/com/datadog/android/nightly/logs/LoggerE2ETests.kt
> +            "$SPECIAL_BUNDLED_TAG_NAME:$tagValue"
It should be on the same line

2021-09-10 08:12 UTC, 0xnm approved these changes

2021-09-13 06:43 UTC, xgouchet approved these changes

2021-09-13 07:09 UTC, merged