RUMM-2090 Print logcat error message when using NoOp implementations
DataDog/dd-sdk-android pull request #895
Opened 2022-04-05 13:53 UTC by mariusc83

### What does this PR do?

In this PR we are aligning the error log messages displayed in the console when the `NoOp` implementation is used for `Logger`, `AndroidTracer` or `RumMonitor` due to the SDK not being initialized yet or the feature not being enabled.

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

2022-04-05 14:42 UTC, 0xnm approved these changes

2022-04-05 15:01 UTC, xgouchet requested changes

2022-04-05 15:07 UTC, mariusc83 commented on dd-sdk-android/src/main/kotlin/com/datadog/android/Datadog.kt
> -    internal const val MESSAGE_DEPRECATED = "%s has been deprecated. " +
was not used

2022-04-06 10:07 UTC, xgouchet approved these changes

2022-04-06 15:08 UTC, merged