app/build.gradle clarification + code snippet
DataDog/dd-sdk-android pull request #896
Opened 2022-04-05 16:45 UTC by gualt1995

### What does this PR do?

Updated the docs.
Clarified that the build.gradle file that needs to be modified is the one in the app directory.
Modified the code snipped to reorder the blocks, added the android block, added //(...) to make it obvious where these lines should be added.

### Motivation

Clarification for less experienced users. 

### Additional Notes

Anything else we should know when reviewing?

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

2022-04-05 16:50 UTC, xgouchet requested changes

2022-04-05 16:50 UTC, xgouchet commented on docs/rum_getting_started.md
> +Declare [dd-sdk-android][1] and the [gradle plugin][12] as a dependency in your `build.gradle` file within your `app`directory
> file within your `app` directory
The "application" module is usually named `app`, but it's not always the case, and a project can have multiple applications.
```suggestion
Declare [dd-sdk-android][1] and the [gradle plugin][12] as a dependency in your application module's `build.gradle` file
```

2022-04-05 17:04 UTC, alai97 approved these changes
Looks good pending Xavier's copy nit!

2022-04-06 07:13 UTC, 0xnm requested changes

2022-04-06 07:13 UTC, 0xnm commented on docs/rum_getting_started.md
>      id("dd-sdk-android-gradle-plugin")
```suggestion
    id("com.datadoghq.dd-sdk-android-gradle-plugin")
```

according to https://plugins.gradle.org/plugin/com.datadoghq.dd-sdk-android-gradle-plugin

2022-04-06 09:26 UTC, 0xnm approved these changes

2022-04-06 09:52 UTC, xgouchet approved these changes

2022-04-07 10:06 UTC, merged