Syncing Changes from Develop to Master
DataDog/dd-sdk-android pull request #965
Opened 2022-06-29 20:16 UTC by alai97

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Additional Notes

Anything else we should know when reviewing?

### Review checklist (to be filled by reviewers)

- [ ] Feature or bugfix MUST have appropriate tests (unit, integration, e2e)
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

2022-06-30 07:03 UTC, 0xnm approved these changes

2022-06-30 12:50 UTC, xgouchet requested changes

2022-06-30 20:15 UTC, alai97 commented on docs/rum_getting_started.md
> +In the initialization snippet, set an environment name, service name, and version number. In the examples below, `APP_VARIANT_NAME` specifies the name of the service that generates data. For more inf
```suggestion
In the initialization snippet, set an environment name, service name, and version number. In the examples below, `APP_VARIANT_NAME` specifies the variant of the application that generates data. For more information, see [Using Tags][14].
```

2022-07-01 07:04 UTC, xgouchet approved these changes

2022-07-01 16:46 UTC, hestonhoffman approved these changes

2022-07-19 20:15 UTC, merged